# Generated by Django 5.0.6 on 2024-05-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zaprafka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='zaprafka/')),
                ('closing_time', models.TimeField()),
                ('opening_time', models.TimeField()),
                ('phone', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(blank=True, to='main.category')),
            ],
        ),
    ]
